# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:  
  name: local 

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: sh '/Users/afuaansah/Desktop/forage_dev/accenture_project/mock-company-webapp/gradlew assemble'
  displayName: 'Build project'

- script: sh '/Users/afuaansah/Desktop/forage_dev/accenture_project/mock-company-webapp/gradlew test'
  displayName: 'Test project'
